### ISSUE TITLE
Manually update eolang version to 0.34.3

### ISSUE THREAD

**Issue by c71n93** [objectionary/sandbox#38]
EO version can't be automatically updated for some reason (#35). 
Need to figure out what's problem, fix it, and update EO version in `pom.xml`.

**Comment by levBagryansky** [comment]
@c71n93 @maxonfjvipon I can do it

**Comment by 0pdd** [comment]
@c71n93 the puzzle [#41](https://github.com/objectionary/sandbox/issues/41) is still not solved.

**Comment by 0pdd** [comment]
@c71n93 the only puzzle [#41](https://github.com/objectionary/sandbox/issues/41) is solved here.
