### ISSUE TITLE
app.eo:3-15: To fix and enable the test below. There are...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/sandbox#41]
The puzzle `38-f0504996` from #38 has to be resolved: 

https://github.com/objectionary/sandbox/blob/49837ed67657b1448eac09fd6003ac51a6bb1772/eo/sandbox/app.eo#L3-L15

The puzzle was created by @levBagryansky on 22-Jan-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by levBagryansky** [comment]
@maxonfjvipon please assign me

**Comment by levBagryansky** [comment]
@yegor256 @maxonfjvipon Since `txt objects` were removed from `home` in pr https://github.com/objectionary/home/pull/201 How to use such objects here?

**Comment by maxonfjvipon** [comment]
@levBagryansky sure
